extends Node2D

var five_letter_words = [
	"CHEER", "PULSE", "MATCH", "PEDAL", "BASIL", "QUEST", "LIVES", "MARCH", "SPORT", "FLARE",
	"DANCE", "QUEEN", "COUCH", "PRICE", "NASAL", "PLUSH", "BLUES", "CHAIN", "NANNY", "HYENA",
	"APPLE", "BREAD", "CLOUD", "DANCE", "EARTH", "FRUIT", "GRAPE", "HORSE", "INSECT", "JUICE",
	"KNIFE", "LEMON", "MUSIC", "NIGHT", "OCEAN", "PEACH", "QUIET", "RAINY", "SNAKE", "TRAIN",
	"UMBRA", "VIPER", "WATER", "XENON", "YEARN", "ZEBRA", "AMBER", "BLACK", "CORAL", "DIVER",
	"EMOTE", "FLUTE", "GLOOM", "HASTE", "JOLLY", "KARMA", "LATCH", "MANGO", "NYMPH", "AUDIO",
	"ADORE", "AUDIT", "AROMA", "OREAD", "URATE", "SAUCE", "ADIEU", "ARISE", "LOUIE", "ABOVE",
	"ACUTE", "ALIVE", "ALONE", "ANGRY", "AWARE", "AWFUL", "BASIC", "BLACK", "BLIND", "BRAVE",
	"BRIEF", "BROAD", "BROWN", "CHEAP", "CHIEF", "CIVIL", "CLEAN", "CLEAR", "CLOSE", "CRAZY",
	"DAILY", "DIRTY", "EARLY", "EMPTY", "EQUAL", "EXACT", "EXTRA", "FAINT", "FALSE", "FINAL"
]

var seven_letter_words = [
	"ABILITY", "ABSENCE", "ACADEMY", "ACCOUNT", "ACCUSED", "ACHIEVE", "ACQUIRE", "ADDRESS", "ADVANCE", "ADVERSE",
	"ADVISED", "ADVISER", "BACKING", "BALANCE", "BANKING", "BARRIER", "BATTERY", "BEARING", "BEATING", "BECAUSE",
	"BEDROOM", "BELIEVE", "CABINET", "CALIBER", "CALLING", "CAPABLE", "CAPITAL", "CAPTAIN", "CAPTION", "CAPTURE",
	"CAREFUL", "CARRIER", "DEALING", "DECIDED", "DECLINE", "DEFAULT", "DEFENCE", "DEFICIT", "DELIVER", "EASTERN",
	"ECONOMY", "EDITION", "ELDERLY", "ELEMENT", "ENGAGED", "ENHANCE", "FACTORY", "FACULTY", "FAILING", "FAILURE",
	"FASHION", "GENERAL", "GREATER", "GALLERY", "GENUINE", "GENETIC", "HOWEVER", "HIMSELF", "HISTORY", "HOLDING",
	"HELPING", "HUNDRED", "INCLUDE", "IMPROVE", "INVOLVE", "INITIAL", "JUSTICE", "JOURNAL", "JOURNEY", "JOINTLY",
	"KINGDOM", "KEEPING", "KITCHEN", "KNOWING", "MACHINE", "MANAGER", "NATURAL", "NEITHER", "NETWORK", "NEUTRAL",
	"OFFICER", "OUTSIDE", "OVERALL", "PASSAGE", "PASSING", "QUALIFY", "RAILWAY", "READILY", "READING", "SCIENCE",
	"SECTION", "TRAFFIC", "TROUBLE", "TEACHER", "UNKNOWN", "UNUSUAL", "YELLOWS", "WAITING", "WALKING", "WORKING"
]

var eleven_letter_words = [
	"ACTINOMETER", "ACTINOMETRY", "ACTINOMYCIN", "ACTUALISTIC", "ACUMINATION", "ACUPRESSURE", "ACUPUNCTURE", "BABYISHNESS",
	"BACCHANALIA", "BACCIFEROUS", "BACCIVOROUS", "BACHELORDOM", "BACHELORISM", "BACILLIFORM", "CALLIGRAPHY", "COLLOCATION",
	"COMPLICATED", "CABBAGEHEAD", "CABBAGELIKE", "CABBAGETOWN", "CACKLEBERRY", "DACARBAZINE", "DACRYORRHEA", "DACTYLOGRAM",
	"DACTYLOLOGY", "DANGLEBERRY", "DAREDEVILRY", "ELEPHANTINE", "ELEPHANTOID", "ELICITATION", "ELIGIBILITY", "ELIMINATION",
	"ELIMINATIVE", "ELIMINATORY", "FABRICATION", "FACILITATOR", "FACTORYLIKE", "GALLERYLIKE", "GALLIMAUFRY", "GALLINACEAN",
	"GALLOWGLASS", "HABITUATION", "HABITUDINAL", "HAGGADISTIC", "ICHNOGRAPHY", "ICHTHYOIDAL", "ICHTHYOLITE", "KABBALISTIC",
	"KAILYARDISM", "KAMELAUKION", "KATAMORPHIC", "LABEFACTION", "LABIODENTAL", "LABRADORITE", "LABYRINTHIC", "MACHICOLATE",
	"MACHINATION", "MACHINEABLE", "NAGGINGNESS", "NAMEABILITY", "NANNOFOSSIL", "NANOMACHINE", "OARSMANSHIP", "OBFUSCATION",
	"OBFUSCATORY", "PARASELENIC", "PARASENSORY", "PARASITICAL", "QUACKSALVER", "QUADRAPHONY", "QUADRASONIC", "QUADRENNIAL",
	"RADIOACTIVE", "RADIOCARBON", "RADIOCESIUM", "REALLOTMENT", "REALPOLITIK", "REALTERABLE", "SACCULATION", "SACRAMENTAL",
	"SACRIFICIAL", "SACROLUMBAR", "SADDLECLOTH", "TACHYGRAPHY", "TACITURNITY", "TAENIACIDAL", "TAGLIATELLE", "TEMPERAMENT",
	"TEMPERATURE", "TEMPESTUOUS", "TELETHERAPY", "ULCEROGENIC", "ULOTRICHOUS", "ULTRAVIOLET", "VACUOLATION", "VALENTINITE",
	"WARRANTABLE", "WHICHSOEVER", "ZEALOUSNESS", "ZESTFULNESS"
]


func get_word() -> String:
	var wordindex = randi()%seven_letter_words.size()
	
	var words = seven_letter_words[wordindex]
	
	return words 
	
	
